# Pipeline básico en YAML para Azure DevOps
# Conéctalo con GitHub y personalízalo para compilar, probar y desplegar tu proyecto.

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Instalación de dependencias
  - script: |
      echo "Instalando dependencias..."
      npm install
    displayName: 'Instalar dependencias'

  # Compilación del proyecto
  - script: |
      echo "Compilando el proyecto..."
      npm run build
    displayName: 'Compilar el proyecto'

  # Ejecutar pruebas
  - script: |
      echo "Ejecutando pruebas..."
      npm test
    displayName: 'Ejecutar pruebas'

  # Despliegue opcional
  - script: |
      echo "Implementando en producción..."
      # Aquí agregarías los comandos necesarios para el despliegue
    displayName: 'Desplegar aplicación'
    condition: succeeded()  # Ejecuta el despliegue solo si los pasos anteriores han sido exitosos
