# Pipeline básico en YAML para Azure DevOps
# Conéctalo con GitHub y personalízalo para compilar, probar y desplegar tu proyecto.

trigger:
  - master  # Ejecuta el pipeline cada vez que se realiza un commit en la rama "master"

pool:
  vmImage: 'ubuntu-latest'  # Especifica la imagen de la máquina que ejecutará el pipeline (Ubuntu más reciente)

steps:
  # Tarea básica para imprimir un mensaje en la consola
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  # Ejemplo de script de múltiples líneas
  - script: |
      echo Agrega otras tareas para construir, probar y desplegar tu proyecto.
      echo Visita https://aka.ms/yaml para más información.
    displayName: 'Run a multi-line script'